name: Testing Workflow

on:
  pull_request:
    branches:
      - develop

jobs:
  testing:
    name: Lint Check and Testing

    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@v2

      - name: Check gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Run Detekt
        run: ./gradlew detekt

      - name: Run Android Linter
        run: ./gradlew lint --stacktrace

      - name: Run Spotless
        run: ./gradlew spotlessKotlinCheck

      - name: Run Unit Tests
        run: ./gradlew testProdDebugUnitTest

      - name: Assemble Debug APK
        run: ./gradlew assembleProdDebug

      - name: Generate Dependency Updates
        run: ./gradlew dependencyUpdates -Drevision=release
