name: Testing Workflow

on:
  pull_request:
    branches:
      - develop

jobs:
  testing:
    name: Lint Check and Testing

    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Run Detekt
        run: ./gradlew detekt

      - name: Run Kotlin Linter
        run: ./gradlew ktlint

      - name: Run Android Linter
        run: ./gradlew lint --stacktrace

      - name: Run Spotless
        run: ./gradlew spotlessKotlinCheck

      - name: Run Unit Tests
        run: ./gradlew testProdDebugUnitTest

      - name: Assemble Debug APK
        run: ./gradlew assembleProdDebug

      - name: Generate Dependency Updates
        run: ./gradlew dependencyUpdates -Drevision=release
